// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe19_oxUFaJjmSn58fMAIjhG32E3VQ51I',
    appId: '1:134936416310:web:8249e05fce3be444790897',
    messagingSenderId: '134936416310',
    projectId: 'theme-park-976a2',
    authDomain: 'theme-park-976a2.firebaseapp.com',
    storageBucket: 'theme-park-976a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXu7kAIgyynSZvQhioaNLzhb9PqD3d_4I',
    appId: '1:134936416310:android:f3091f8aece2eec5790897',
    messagingSenderId: '134936416310',
    projectId: 'theme-park-976a2',
    storageBucket: 'theme-park-976a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCpN8mH-4xsW-8N7uJoneGZ6PZ6vEam34',
    appId: '1:134936416310:ios:a08d44156ed9448b790897',
    messagingSenderId: '134936416310',
    projectId: 'theme-park-976a2',
    storageBucket: 'theme-park-976a2.appspot.com',
    iosBundleId: 'com.example.notDoingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCpN8mH-4xsW-8N7uJoneGZ6PZ6vEam34',
    appId: '1:134936416310:ios:a08d44156ed9448b790897',
    messagingSenderId: '134936416310',
    projectId: 'theme-park-976a2',
    storageBucket: 'theme-park-976a2.appspot.com',
    iosBundleId: 'com.example.notDoingFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe19_oxUFaJjmSn58fMAIjhG32E3VQ51I',
    appId: '1:134936416310:web:6ebefe92751b6f15790897',
    messagingSenderId: '134936416310',
    projectId: 'theme-park-976a2',
    authDomain: 'theme-park-976a2.firebaseapp.com',
    storageBucket: 'theme-park-976a2.appspot.com',
  );

}